#用户名 密码配置
security:
  user:
   name: admin
   password: admin
file:
  upload-dir: ./uploads

server:
  port: 9992
 
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    mode: LEGACYHTML5
    
myapp:
  mail:
    smtp-servers:
      - 10.1.1.1
      - 10.1.1.2
      - 10.1.1.3
    user: sikongming
    password: 100200
    enabled: false