#用户名 密码配置
security:
  user:
   name: admin
   password: admin
file:
  upload-dir: ./uploads

server:
  port: 9992
 
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    mode: LEGACYHTML5
    
myapp:
  mail:
    smtp-servers:
      - 10.1.1.1
      - 10.1.1.2
      - 10.1.1.3
    maps: 
      USD: https://xxx.oss-ap-southeast-1.aliyuncs.com/reconciliation_sample.pdf,
      AED: https://xxx.oss-ap-southeast-1.aliyuncs.com/reconciliation_sample.pdf,
      BTC: https://btc.com/,
      ETH: https://etherscan.io/,
      LTC: https://live.blockcypher.com/ltc/,
      BCH: https://bch.btc.com/}
    user: sikongming
    password: 100200
    enabled: false
    userBean:
      name: skm
      age: 30
    userList:
      - {
        name: piaojinmei,
        age: 32
      }
      - {
        name: sikongxu,
        age: 2
      }